/**
 * Seeds ALL 44 frontend catalog products into the Turso DB.
 *
 * The frontend src/lib/data/catalog-products.ts has 44 products (p001-p044)
 * with hardcoded data. This script puts them all in the backend DB so the
 * API can serve them instead of using fallback data.
 *
 * Idempotent — safe to re-run. Uses INSERT OR REPLACE for products so
 * prices/stock can be updated on re-run.
 *
 * Run:
 *   cd backend && npx tsx --env-file=.env src/scripts/seed-all-products.ts
 */
import { createClient } from "@libsql/client";

interface SeedProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  shortDescription: string;
  sku: string;
  categorySlug: string;
  brandName: string;
  basePrice: number;
  salePrice: number | null;
  costPrice: number;
  isFeatured: boolean;
  isBestSeller: boolean;
  isNewArrival: boolean;
  stockQuantity: number;
  lowStockThreshold: number;
  tags: string[];
  size: string;
  origin: string;
  madeInNepal: boolean;
  skinTypes: string[];
  concernTags: string[];
  benefits: string[];
  ingredients: string[];
  howToUse: string[];
  imageUrl: string;
}

const CATEGORY_MAP: Record<string, string> = {
  skincare: "cat-skincare",
  makeup: "cat-makeup",
  haircare: "cat-haircare",
  bodycare: "cat-bodycare",
  fragrance: "cat-fragrance",
  tools: "cat-tools",
};

const ALL_PRODUCTS: SeedProduct[] = [
  { id: "p001", name: "COSRX Advanced Snail 96 Mucin Power Essence", slug: "cosrx-advanced-snail-96-mucin-power-essence", description: "A cult Korean essence with 96% snail secretion filtrate for a plump, hydrated-looking complexion. Lightweight, non-sticky and layers beautifully under moisturiser and SPF — a K-beauty routine staple for Kathmandu weather.", shortDescription: "96% snail mucin hydrating essence — K-beauty staple", sku: "GLM-COSRX-SNAIL-100", categorySlug: "skincare", brandName: "COSRX", basePrice: 325000, salePrice: 289000, costPrice: 205000, isFeatured: true, isBestSeller: true, isNewArrival: false, stockQuantity: 36, lowStockThreshold: 5, tags: ["Hydration", "Barrier Repair", "K-Beauty", "best-seller"], size: "100 ml", origin: "Korea", madeInNepal: false, skinTypes: ["All Skin Types", "Combination"], concernTags: ["Hydration", "Barrier Repair", "K-Beauty"], benefits: ["Cushiony hydrating essence", "Layers well under cream", "K-beauty routine staple"], ingredients: ["Snail secretion filtrate", "Betaine", "Allantoin"], howToUse: ["Pat onto clean skin after toner", "Follow with moisturizer", "Use morning or night"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p002", name: "Cetaphil Gentle Skin Cleanser", slug: "cetaphil-gentle-skin-cleanser", description: "A gentle cleanser option for simple, low-irritation routines.", shortDescription: "Non-stripping daily cleanser for sensitive skin", sku: "GLM-CET-GSC-125", categorySlug: "skincare", brandName: "Cetaphil", basePrice: 135000, salePrice: 119000, costPrice: 75000, isFeatured: true, isBestSeller: false, isNewArrival: true, stockQuantity: 54, lowStockThreshold: 5, tags: ["Sensitive Skin", "Barrier Repair", "new-arrival"], size: "125 ml", origin: "International", madeInNepal: false, skinTypes: ["Sensitive", "Dry", "All Skin Types"], concernTags: ["Sensitive Skin", "Barrier Repair"], benefits: ["Non-stripping daily cleanse", "Good starter routine", "Comfortable for sensitive skin"], howToUse: ["Massage on damp skin", "Rinse or tissue off", "Use morning and night"], ingredients: ["Glycerin", "Niacinamide", "Panthenol"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p003", name: "Beauty of Joseon Relief Sun SPF50+", slug: "beauty-of-joseon-relief-sun-spf50", description: "A lightweight Korean chemical sunscreen with rice extract and probiotics for a comfortable, skin-like finish with no white cast.", shortDescription: "Rice + probiotic SPF50+ — no white cast, daily wear", sku: "GLM-BOJ-RSUN-50", categorySlug: "skincare", brandName: "Beauty of Joseon", basePrice: 279000, salePrice: 245000, costPrice: 165000, isFeatured: true, isBestSeller: true, isNewArrival: false, stockQuantity: 42, lowStockThreshold: 8, tags: ["Sun Protection", "No White Cast", "K-Beauty", "best-seller"], size: "50 ml", origin: "Korea", madeInNepal: false, skinTypes: ["All Skin Types", "Oily", "Sensitive"], concernTags: ["Sun Protection", "No White Cast", "K-Beauty"], benefits: ["Comfortable daily SPF", "Soft skin-like finish", "No white cast"], ingredients: ["Rice extract", "Probiotics", "Modern UV filters"], howToUse: ["Apply two-finger amount as last AM step", "Reapply during outdoor days"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p004", name: "The Ordinary Niacinamide 10% + Zinc 1%", slug: "the-ordinary-niacinamide-10-zinc-1", description: "A direct active serum for oily and combination-skin routines.", shortDescription: "Niacinamide 10% + zinc — shine control serum", sku: "GLM-ORD-NIA-30", categorySlug: "skincare", brandName: "The Ordinary", basePrice: 215000, salePrice: 189000, costPrice: 105000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 47, lowStockThreshold: 5, tags: ["Oil Control", "Pore Care"], size: "30 ml", origin: "Canada", madeInNepal: false, skinTypes: ["Oily", "Combination", "Acne-Prone"], concernTags: ["Oil Control", "Pore Care"], benefits: ["Helps balance shine", "Serum texture", "Routine-friendly active"], howToUse: ["Use after cleansing", "Start once daily", "Follow with moisturizer and SPF"], ingredients: ["Niacinamide", "Zinc PCA"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p005", name: "Innisfree Green Tea Seed Hyaluronic Serum", slug: "innisfree-green-tea-seed-hyaluronic-serum", description: "A fresh, dewy serum inspired by Korean hydration routines.", shortDescription: "Green tea + hyaluronic acid — dewy hydration serum", sku: "GLM-INS-GTS-80", categorySlug: "skincare", brandName: "Innisfree", basePrice: 365000, salePrice: 329000, costPrice: 215000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 30, lowStockThreshold: 5, tags: ["Hydration", "Dullness", "K-Beauty", "new-arrival"], size: "80 ml", origin: "Korea", madeInNepal: false, skinTypes: ["All Skin Types", "Dry", "Combination"], concernTags: ["Hydration", "Dullness", "K-Beauty"], benefits: ["Fresh water-serum feel", "Hydrating first-serum step", "Good under sunscreen"], howToUse: ["Apply after toner", "Layer moisturizer over it"], ingredients: ["Green tea extract", "Hyaluronic acid", "Glycerin"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p006", name: "CeraVe Moisturising Cream", slug: "cerave-moisturising-cream", description: "A barrier-support cream for dry and sensitive-feeling skin.", shortDescription: "Ceramide cream for barrier repair — face & body", sku: "GLM-CRV-MC-177", categorySlug: "skincare", brandName: "CeraVe", basePrice: 315000, salePrice: 285000, costPrice: 195000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 25, lowStockThreshold: 5, tags: ["Barrier Repair", "Hydration"], size: "177 ml", origin: "International", madeInNepal: false, skinTypes: ["Dry", "Sensitive", "All Skin Types"], concernTags: ["Barrier Repair", "Hydration"], benefits: ["Rich comfort cream", "Ceramide-led routine", "Face and body friendly"], howToUse: ["Apply after serum", "Use extra on dry areas"], ingredients: ["Ceramides", "Hyaluronic acid", "Glycerin"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p007", name: "Bioderma Sensibio H2O Micellar Water", slug: "bioderma-sensibio-h2o-micellar-water", description: "A gentle micellar-water staple for makeup removal and first cleansing.", shortDescription: "Micellar water for sensitive skin — no-rinse", sku: "GLM-BIO-SENS-250", categorySlug: "skincare", brandName: "Bioderma", basePrice: 245000, salePrice: 219000, costPrice: 155000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 31, lowStockThreshold: 5, tags: ["Makeup Removal", "Sensitive Skin"], size: "250 ml", origin: "France", madeInNepal: false, skinTypes: ["Sensitive", "All Skin Types"], concernTags: ["Makeup Removal", "Sensitive Skin"], benefits: ["Gentle first cleanse", "Removes light makeup", "No-rinse style"], howToUse: ["Soak cotton pad", "Sweep over face", "Follow with cleanser if needed"], ingredients: ["Micelles", "Cucumber extract"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p008", name: "La Roche-Posay Anthelios UVMune SPF50+", slug: "la-roche-posay-anthelios-uvmune-spf50", description: "A premium sunscreen edit for high-protection daily wear.", shortDescription: "High-protection SPF50+ fluid sunscreen", sku: "GLM-LRP-ANT-50", categorySlug: "skincare", brandName: "La Roche-Posay", basePrice: 399000, salePrice: 365000, costPrice: 275000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 18, lowStockThreshold: 5, tags: ["Sun Protection", "No White Cast"], size: "50 ml", origin: "France", madeInNepal: false, skinTypes: ["All Skin Types", "Sensitive"], concernTags: ["Sun Protection", "No White Cast"], benefits: ["High protection SPF", "Fluid texture", "Good for city routines"], howToUse: ["Shake well", "Apply generously", "Reapply outdoors"], ingredients: ["UV filters", "Thermal water"], imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=900&q=86&fit=crop&auto=format" },
  { id: "p009", name: "Maybelline Fit Me Matte + Poreless Foundation", slug: "maybelline-fit-me-matte-poreless-foundation", description: "A familiar base product for everyday and event makeup routines.", shortDescription: "Matte foundation with buildable coverage", sku: "GLM-MAY-FITME-30", categorySlug: "makeup", brandName: "Maybelline", basePrice: 129000, salePrice: 109000, costPrice: 65000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 67, lowStockThreshold: 5, tags: ["Seamless Base", "Long Wear"], size: "30 ml", origin: "International", madeInNepal: false, skinTypes: ["Oily", "Combination"], concernTags: ["Seamless Base", "Long Wear"], benefits: ["Everyday matte base", "Buildable coverage", "Good entry foundation"], howToUse: ["Apply with sponge or brush", "Blend from center outward"], ingredients: ["Pigments", "Silica", "Glycerin"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p010", name: "Lakme 9to5 Primer + Matte Lip Color", slug: "lakme-9to5-primer-matte-lip-color", description: "A classic long-wear lipstick edit for Nepali office and event looks.", shortDescription: "Long-wear matte lipstick for office & events", sku: "GLM-LAK-9TO5-LIP", categorySlug: "makeup", brandName: "Lakme", basePrice: 92500, salePrice: 78000, costPrice: 40000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 52, lowStockThreshold: 5, tags: ["Long Wear", "Festival"], size: "3.6 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Long Wear", "Festival"], benefits: ["Polished matte lip", "Office to evening color", "Easy gifting"], howToUse: ["Apply directly", "Blot and layer"], ingredients: ["Color pigments", "Waxes", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=86&fit=crop&auto=format" },
  { id: "p011", name: "Cream Blush Stick - Peach Bloom", slug: "cream-blush-stick-peach-bloom", description: "A creamy blush stick for quick color that looks fresh, not powdery.", shortDescription: "Creamy blush stick with fresh finish", sku: "GLM-MKP-BLS-7", categorySlug: "makeup", brandName: "GLAMO Edit", basePrice: 125000, salePrice: null, costPrice: 55000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 33, lowStockThreshold: 5, tags: ["Dewy Finish"], size: "7 g", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Dewy Finish"], benefits: ["Creamy blend", "Fresh cheek tint", "Doubles as lip tint"], howToUse: ["Swipe lightly on cheeks", "Blend with fingers or sponge"], ingredients: ["Jojoba esters", "Mineral pigments", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p012", name: "Argan Smooth Hair Serum", slug: "argan-smooth-hair-serum", description: "A lightweight finishing serum for dry ends, flyaways and monsoon frizz.", shortDescription: "Argan oil serum for frizz control & shine", sku: "GLM-HAR-ARG-50", categorySlug: "haircare", brandName: "Natura Nepal", basePrice: 135000, salePrice: null, costPrice: 65000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 26, lowStockThreshold: 5, tags: ["Frizz Control", "Shine"], size: "50 ml", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Frizz Control", "Shine"], benefits: ["Smooths frizz", "Adds soft shine", "Helps detangle ends"], howToUse: ["Warm 1-2 pumps in palms", "Apply to mid-lengths and ends", "Use on damp or dry hair"], ingredients: ["Argan oil", "Silicone blend", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=900&q=86&fit=crop&auto=format" },
  { id: "p013", name: "Amla Strength Hair Oil", slug: "amla-strength-hair-oil", description: "A classic pre-wash hair oil ritual with amla-inspired care.", shortDescription: "Amla & coconut pre-wash hair oil", sku: "GLM-HAR-AMLA-100", categorySlug: "haircare", brandName: "Himalayan Botanics", basePrice: 52000, salePrice: null, costPrice: 25000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 48, lowStockThreshold: 5, tags: ["Scalp Care", "Shine"], size: "100 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Scalp Care", "Shine"], benefits: ["Pre-wash nourishment", "Traditional oil ritual", "Adds healthy-looking shine"], howToUse: ["Massage into scalp and lengths", "Leave for 30 minutes or overnight", "Shampoo thoroughly"], ingredients: ["Amla extract", "Coconut oil", "Sesame oil"], imageUrl: "https://images.unsplash.com/photo-1526758097130-bab247274f58?w=900&q=86&fit=crop&auto=format" },
  { id: "p014", name: "Rice Protein Repair Shampoo", slug: "rice-protein-repair-shampoo", description: "A gentle repair-focused shampoo for hair that feels dry after heat styling or pollution.", shortDescription: "Rice protein repair shampoo for damaged hair", sku: "GLM-HAR-RPR-250", categorySlug: "haircare", brandName: "Natura Nepal", basePrice: 105000, salePrice: 89000, costPrice: 45000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 36, lowStockThreshold: 5, tags: ["Frizz Control", "Damage Care", "new-arrival"], size: "250 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Frizz Control", "Damage Care"], benefits: ["Cleans without a rough feel", "Supports smoother lengths", "Family-friendly value size"], howToUse: ["Massage into wet scalp", "Rinse well", "Follow with conditioner"], ingredients: ["Rice protein", "Aloe", "Mild surfactants"], imageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=900&q=86&fit=crop&auto=format" },
  { id: "p015", name: "Shea Soft Body Lotion", slug: "shea-soft-body-lotion", description: "A daily body lotion for soft, comfortable skin through dry or windy days.", shortDescription: "Shea butter body lotion for daily moisture", sku: "GLM-BDY-SHEA-200", categorySlug: "bodycare", brandName: "GLAMO Edit", basePrice: 78000, salePrice: null, costPrice: 35000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 41, lowStockThreshold: 5, tags: ["Hydration", "Dry Skin"], size: "200 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types", "Dry"], concernTags: ["Hydration", "Dry Skin"], benefits: ["Softens dry skin", "Quick everyday use", "Comfortable after shower"], howToUse: ["Apply generously after bath", "Reapply on elbows, knees and hands"], ingredients: ["Shea butter", "Glycerin", "Sunflower oil"], imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=900&q=86&fit=crop&auto=format" },
  { id: "p016", name: "Coffee Body Polish", slug: "coffee-body-polish", description: "A sensorial body polish for weekly shower rituals.", shortDescription: "Coffee & sugar body scrub for smooth skin", sku: "GLM-BDY-COF-150", categorySlug: "bodycare", brandName: "Kathmandu Glow", basePrice: 98000, salePrice: null, costPrice: 42000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 14, lowStockThreshold: 5, tags: ["Smooth Skin"], size: "150 g", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Smooth Skin"], benefits: ["Buffs rough texture", "Warm coffee aroma", "Leaves skin soft"], howToUse: ["Massage on damp skin", "Rinse thoroughly", "Use 1-2 times weekly"], ingredients: ["Coffee grounds", "Sugar", "Coconut oil"], imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=900&q=86&fit=crop&auto=format" },
  { id: "p017", name: "Mogra & Sandalwood Eau de Parfum", slug: "mogra-sandalwood-eau-de-parfum", description: "A warm floral perfume with a polished, gift-ready feel.", shortDescription: "Floral sandalwood perfume for evening wear", sku: "GLM-FRG-MOG-30", categorySlug: "fragrance", brandName: "Luxe Aura", basePrice: 365000, salePrice: 320000, costPrice: 210000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 12, lowStockThreshold: 5, tags: ["Long Wear"], size: "30 ml", origin: "UAE", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Long Wear"], benefits: ["Soft floral warmth", "Evening-friendly", "Giftable size"], howToUse: ["Spray on pulse points", "Avoid rubbing wrists together"], ingredients: ["Fragrance blend", "Alcohol denat.", "Water"], imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=900&q=86&fit=crop&auto=format" },
  { id: "p018", name: "Rose Mist Body Splash", slug: "rose-mist-body-splash", description: "A light rose body mist for daily freshness.", shortDescription: "Light rose body mist for daily freshness", sku: "GLM-FRG-ROS-100", categorySlug: "fragrance", brandName: "Himalayan Botanics", basePrice: 85000, salePrice: null, costPrice: 35000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 29, lowStockThreshold: 5, tags: ["Freshness", "new-arrival"], size: "100 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Freshness"], benefits: ["Light everyday scent", "Refreshes after commute", "Layerable with lotion"], howToUse: ["Mist onto body from 15 cm away", "Reapply as desired"], ingredients: ["Rose accord", "Aloe water", "Alcohol denat."], imageUrl: "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=900&q=86&fit=crop&auto=format" },
  { id: "p019", name: "Precision Makeup Sponge Duo", slug: "precision-makeup-sponge-duo", description: "A sponge duo for blending concealer, tint and foundation more evenly.", shortDescription: "2-piece makeup sponge set for flawless base", sku: "GLM-TOL-SPG-2", categorySlug: "tools", brandName: "Beauty Tools", basePrice: 59000, salePrice: null, costPrice: 18000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 44, lowStockThreshold: 5, tags: ["Seamless Base"], size: "2 pieces", origin: "China", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Seamless Base"], benefits: ["Soft bounce", "Damp or dry use", "Two shapes for detail and base"], howToUse: ["Dampen and squeeze excess water", "Bounce product onto skin", "Wash weekly"], ingredients: ["Latex-free sponge material"], imageUrl: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=900&q=86&fit=crop&auto=format" },
  { id: "p020", name: "Essential Brush Set", slug: "essential-brush-set", description: "A starter brush set for everyday makeup routines.", shortDescription: "7-piece synthetic brush set with travel pouch", sku: "GLM-TOL-BRS-7", categorySlug: "tools", brandName: "Beauty Tools", basePrice: 185000, salePrice: null, costPrice: 75000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 17, lowStockThreshold: 5, tags: ["Seamless Base"], size: "7 pieces", origin: "China", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Seamless Base"], benefits: ["Face and eye basics", "Soft synthetic bristles", "Travel pouch included"], howToUse: ["Use larger brushes for base", "Use smaller brushes for eyes and detail", "Clean regularly"], ingredients: ["Synthetic bristles", "Aluminium ferrule", "Wood handle"], imageUrl: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=900&q=86&fit=crop&auto=format" },
  { id: "p021", name: "Cica Recovery Sheet Mask", slug: "cica-recovery-sheet-mask", description: "A calming mask for days when skin feels warm, tight or stressed.", shortDescription: "Centella asiatica sheet mask for sensitive skin", sku: "GLM-SKN-CICA-1", categorySlug: "skincare", brandName: "Derma Lab", basePrice: 25000, salePrice: null, costPrice: 8000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 72, lowStockThreshold: 10, tags: ["Sensitive Skin", "Hydration"], size: "1 sheet", origin: "Korea", madeInNepal: false, skinTypes: ["Sensitive", "All Skin Types"], concernTags: ["Sensitive Skin", "Hydration"], benefits: ["Cooling single-use mask", "Good after sun exposure", "Travel-friendly"], howToUse: ["Apply after cleansing and toner", "Leave on for 10-15 minutes", "Pat remaining essence"], ingredients: ["Centella asiatica", "Madecassoside", "Hyaluronic acid"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p022", name: "Kajal Definer Pencil", slug: "kajal-definer-pencil", description: "A classic kajal pencil for defined everyday eyes.", shortDescription: "Deep black kajal pencil for everyday eyes", sku: "GLM-MKP-KAJ-01", categorySlug: "makeup", brandName: "Kathmandu Glow", basePrice: 42000, salePrice: null, costPrice: 15000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 31, lowStockThreshold: 5, tags: ["Long Wear"], size: "1.2 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Long Wear"], benefits: ["Smooth glide", "Deep black payoff", "Easy to sharpen"], howToUse: ["Glide along lash line", "Smudge quickly for softer look"], ingredients: ["Wax blend", "Carbon black pigment", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p023", name: "Papaya Enzyme Face Wash", slug: "papaya-enzyme-face-wash", description: "A brightening-style daily face wash for fresh, clean skin without a tight feel.", shortDescription: "Papaya enzyme face wash for brightening", sku: "GLM-SKN-PAP-100", categorySlug: "skincare", brandName: "Himalayan Botanics", basePrice: 79000, salePrice: 69000, costPrice: 30000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 40, lowStockThreshold: 5, tags: ["Brightening", "Oil Control"], size: "100 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types", "Oily", "Combination"], concernTags: ["Brightening", "Oil Control"], benefits: ["Fresh morning cleanse", "Leaves skin comfortable", "Mild enzyme-inspired formula"], howToUse: ["Massage on wet face", "Rinse thoroughly", "Avoid eye area"], ingredients: ["Papaya extract", "Aloe", "Mild cleansing agents"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p024", name: "Overnight Lip Sleeping Balm", slug: "overnight-lip-sleeping-balm", description: "A comfortable overnight lip balm for dry, flaky lips.", shortDescription: "Overnight lip sleeping balm for dry lips", sku: "GLM-SKN-LIP-15", categorySlug: "skincare", brandName: "GLAMO Edit", basePrice: 72000, salePrice: null, costPrice: 28000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 22, lowStockThreshold: 5, tags: ["Hydration", "Dry Lips", "new-arrival"], size: "15 g", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Hydration", "Dry Lips"], benefits: ["Cushiony night balm", "Softens dry lips", "Subtle berry scent"], howToUse: ["Apply a generous layer before sleep", "Use a thin layer in daytime if needed"], ingredients: ["Lanolin alternative", "Berry extract", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=900&q=86&fit=crop&auto=format" },
  { id: "p025", name: "Plum Rice Water Hybrid Sunscreen SPF 50", slug: "plum-rice-water-hybrid-sunscreen-spf-50", description: "A brightening-style daily sunscreen with niacinamide and rice water.", shortDescription: "Rice water + niacinamide hybrid SPF50, no white cast", sku: "GLM-SUN-PLM-50", categorySlug: "skincare", brandName: "Plum", basePrice: 80000, salePrice: 69500, costPrice: 38000, isFeatured: true, isBestSeller: false, isNewArrival: true, stockQuantity: 36, lowStockThreshold: 8, tags: ["Sun Protection", "No White Cast", "Brightening", "new-arrival"], size: "50 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types", "Combination", "Oily"], concernTags: ["Sun Protection", "No White Cast", "Brightening"], benefits: ["Hybrid daily SPF finish", "Comfortable for commute days", "Pairs well under light makeup"], howToUse: ["Use as the last morning skincare step", "Apply a two-finger amount", "Reapply during long outdoor exposure"], ingredients: ["Niacinamide", "Rice water", "Hybrid UV filters"], imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=900&q=86&fit=crop&auto=format" },
  { id: "p026", name: "COSRX Acne Pimple Patch 24 Patches", slug: "cosrx-acne-pimple-patch-24", description: "A compact pimple patch for quick spot-care moments.", shortDescription: "Hydrocolloid pimple patches for targeted care", sku: "GLM-SKN-COS-PATCH", categorySlug: "skincare", brandName: "COSRX", basePrice: 70000, salePrice: 60000, costPrice: 30000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 84, lowStockThreshold: 10, tags: ["Acne Care", "K-Beauty", "Sensitive Skin"], size: "24 patches", origin: "Korea", madeInNepal: false, skinTypes: ["Acne-Prone", "Oily", "All Skin Types"], concernTags: ["Acne Care", "K-Beauty", "Sensitive Skin"], benefits: ["Easy spot-cover format", "Useful for targeted care", "Travel and pouch friendly"], howToUse: ["Apply on clean dry skin", "Leave until patch turns opaque", "Do not apply over cream or oil"], ingredients: ["Hydrocolloid dressing"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p027", name: "Cetaphil Gentle Skin Cleanser 125 ml", slug: "cetaphil-gentle-skin-cleanser-125ml", description: "A gentle cleanser benchmark for sensitive-skin shoppers.", shortDescription: "Trusted gentle cleanser for sensitive skin", sku: "GLM-SKN-CET-CLE-125", categorySlug: "skincare", brandName: "Cetaphil", basePrice: 155000, salePrice: 130000, costPrice: 85000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 58, lowStockThreshold: 5, tags: ["Sensitive Skin", "Barrier Repair", "Hydration"], size: "125 ml", origin: "Canada", madeInNepal: false, skinTypes: ["Sensitive", "Dry", "All Skin Types"], concernTags: ["Sensitive Skin", "Barrier Repair", "Hydration"], benefits: ["Gentle cleanse positioning", "Good for simple routines", "Non-stripping feel"], howToUse: ["Massage onto damp skin", "Rinse or wipe gently", "Follow with moisturizer"], ingredients: ["Glycerin", "Mild cleansing agents", "Skin-conditioning blend"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p028", name: "Bioderma Sensibio Micellar Water 250 ml", slug: "bioderma-sensibio-micellar-water-250ml", description: "A no-rinse cleansing-water for makeup removal and sensitive-skin routines.", shortDescription: "Micellar water for gentle makeup removal", sku: "GLM-SKN-BIO-MIC-250", categorySlug: "skincare", brandName: "Bioderma", basePrice: 165000, salePrice: 145000, costPrice: 100000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 41, lowStockThreshold: 5, tags: ["Makeup Removal", "Sensitive Skin"], size: "250 ml", origin: "France", madeInNepal: false, skinTypes: ["Sensitive", "All Skin Types"], concernTags: ["Makeup Removal", "Sensitive Skin"], benefits: ["Removes light makeup", "No-rinse convenience", "Good first-cleanse option"], howToUse: ["Soak a cotton pad", "Sweep gently over face and lips", "Follow with cleanser if wearing heavy makeup"], ingredients: ["Micellar cleansing agents", "Purified water", "Soothing blend"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p029", name: "Anua Heartleaf 77 Soothing Toner", slug: "anua-heartleaf-77-soothing-toner", description: "A soothing toner for customers exploring Korean skincare steps.", shortDescription: "Heartleaf soothing toner for sensitive skin", sku: "GLM-SKN-ANU-TON-150", categorySlug: "skincare", brandName: "Anua", basePrice: 255000, salePrice: 225000, costPrice: 155000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 24, lowStockThreshold: 5, tags: ["Sensitive Skin", "Hydration", "K-Beauty", "new-arrival"], size: "150 ml", origin: "Korea", madeInNepal: false, skinTypes: ["Sensitive", "Combination", "All Skin Types"], concernTags: ["Sensitive Skin", "Hydration", "K-Beauty"], benefits: ["Light watery layers", "Comforts redness-prone routines", "Preps skin before serum"], howToUse: ["Pat onto clean skin", "Layer once or twice as needed", "Follow with serum or moisturizer"], ingredients: ["Heartleaf extract", "Glycerin", "Panthenol"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p030", name: "Beauty of Joseon Relief Sun Rice SPF 50+", slug: "beauty-of-joseon-relief-sun-rice-spf-50", description: "A premium K-beauty sunscreen for shoppers who prefer a moisturizing SPF feel.", shortDescription: "Premium rice SPF50+ for moisturizing protection", sku: "GLM-SUN-BOJ-RICE-50", categorySlug: "skincare", brandName: "Beauty of Joseon", basePrice: 235000, salePrice: 210000, costPrice: 145000, isFeatured: true, isBestSeller: true, isNewArrival: false, stockQuantity: 30, lowStockThreshold: 8, tags: ["Sun Protection", "K-Beauty", "No White Cast"], size: "50 ml", origin: "Korea", madeInNepal: false, skinTypes: ["All Skin Types", "Dry", "Combination"], concernTags: ["Sun Protection", "K-Beauty", "No White Cast"], benefits: ["Creamy but comfortable texture", "Good for everyday SPF users", "Works under soft makeup"], howToUse: ["Apply generously every morning", "Reapply every few hours outdoors", "Use after moisturizer if skin is dry"], ingredients: ["Rice extract", "Modern UV filters", "Green tea complex"], imageUrl: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=900&q=86&fit=crop&auto=format" },
  { id: "p031", name: "Maybelline Fit Me Matte Foundation", slug: "maybelline-fit-me-matte-foundation", description: "A familiar base-product with shade-selection UX for GLAMO makeup flows.", shortDescription: "Matte foundation with shade options", sku: "GLM-MKP-MAY-FIT-30", categorySlug: "makeup", brandName: "Maybelline", basePrice: 135000, salePrice: 115000, costPrice: 65000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 47, lowStockThreshold: 5, tags: ["Long Wear", "Seamless Base", "Oil Control"], size: "30 ml", origin: "India", madeInNepal: false, skinTypes: ["Oily", "Combination", "All Skin Types"], concernTags: ["Long Wear", "Seamless Base", "Oil Control"], benefits: ["Soft matte base", "Everyday coverage", "Shade-range ready UI"], howToUse: ["Shake before use", "Blend thin layers with sponge or brush", "Set oily areas lightly"], ingredients: ["Soft-focus powders", "Pigment blend", "Film former"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p032", name: "Lakme 9 to 5 Primer Matte Lip Color", slug: "lakme-9-to-5-primer-matte-lip-color", description: "A long-wear lipstick for daily office and event makeup looks.", shortDescription: "Matte long-wear lipstick for office looks", sku: "GLM-MKP-LAK-LIP-01", categorySlug: "makeup", brandName: "Lakme", basePrice: 90000, salePrice: 75000, costPrice: 35000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 63, lowStockThreshold: 5, tags: ["Long Wear"], size: "3.6 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Long Wear"], benefits: ["Office-friendly matte look", "Pigmented color payoff", "Shade selector ready"], howToUse: ["Apply on moisturized lips", "Blot once for a softer stain", "Layer for evening color"], ingredients: ["Wax blend", "Color pigments", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=900&q=86&fit=crop&auto=format" },
  { id: "p033", name: "SUGAR Cosmetics Kohl of Honour Kajal", slug: "sugar-cosmetics-kohl-of-honour-kajal", description: "A kohl-style kajal for eye makeup and product-comparison coverage.", shortDescription: "Kohl kajal for dramatic eye definition", sku: "GLM-MKP-SUG-KAJ-01", categorySlug: "makeup", brandName: "SUGAR Cosmetics", basePrice: 102000, salePrice: 89000, costPrice: 42000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 39, lowStockThreshold: 5, tags: ["Long Wear"], size: "0.25 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Long Wear"], benefits: ["Deep eye definition", "Smudge-style looks", "Compact for handbags"], howToUse: ["Apply along lash line", "Use short strokes", "Smudge quickly for smoky effect"], ingredients: ["Wax blend", "Pigment blend", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p034", name: "Swiss Beauty Liquid Concealer", slug: "swiss-beauty-liquid-concealer", description: "A practical concealer for base routines and checkout testing.", shortDescription: "Creamy liquid concealer with shade options", sku: "GLM-MKP-SWB-CON-6", categorySlug: "makeup", brandName: "Swiss Beauty", basePrice: 65000, salePrice: 52000, costPrice: 22000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 54, lowStockThreshold: 5, tags: ["Seamless Base", "Long Wear"], size: "6 g", origin: "China", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Seamless Base", "Long Wear"], benefits: ["Spot and under-eye coverage", "Creamy blendable texture", "Budget-friendly makeup staple"], howToUse: ["Dot onto targeted areas", "Blend with sponge or fingertip", "Set lightly if needed"], ingredients: ["Pigment blend", "Glycerin", "Soft-focus powder"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p035", name: "Mamaearth Onion Hair Fall Control Shampoo", slug: "mamaearth-onion-hair-fall-control-shampoo", description: "A haircare for customers browsing scalp and hair-fall routine categories.", shortDescription: "Onion shampoo for hair fall control", sku: "GLM-HAR-MAM-ONI-250", categorySlug: "haircare", brandName: "Mamaearth", basePrice: 85000, salePrice: 72000, costPrice: 35000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 45, lowStockThreshold: 5, tags: ["Hair Fall", "Scalp Care"], size: "250 ml", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Hair Fall", "Scalp Care"], benefits: ["Daily wash positioning", "Supports cleaner scalp feel", "Pairs with conditioner"], howToUse: ["Apply to wet scalp", "Massage gently", "Rinse and repeat if needed"], ingredients: ["Onion extract", "Plant protein", "Mild cleansing agents"], imageUrl: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=900&q=86&fit=crop&auto=format" },
  { id: "p036", name: "Himalaya Purifying Neem Face Wash", slug: "himalaya-purifying-neem-face-wash", description: "A starter face-wash for oily and blemish-prone routines.", shortDescription: "Neem face wash for oily & acne-prone skin", sku: "GLM-SKN-HIM-NEEM-100", categorySlug: "skincare", brandName: "Himalaya", basePrice: 42500, salePrice: 37500, costPrice: 15000, isFeatured: false, isBestSeller: true, isNewArrival: false, stockQuantity: 96, lowStockThreshold: 10, tags: ["Acne Care", "Oil Control"], size: "100 ml", origin: "India", madeInNepal: false, skinTypes: ["Oily", "Acne-Prone", "Combination"], concernTags: ["Acne Care", "Oil Control"], benefits: ["Budget daily cleanser", "Fresh gel texture", "Teen and starter routine friendly"], howToUse: ["Massage on wet skin", "Avoid the eye area", "Rinse well and moisturize"], ingredients: ["Neem extract", "Turmeric extract", "Mild cleansing base"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p037", name: "Aroma Magic Mineral Glow Scrub", slug: "aroma-magic-mineral-glow-scrub", description: "A weekly facial-scrub for routine-building and product education sections.", shortDescription: "Mineral scrub for weekly glow ritual", sku: "GLM-SKN-ARM-SCR-100", categorySlug: "skincare", brandName: "Aroma Magic", basePrice: 70000, salePrice: 62000, costPrice: 28000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 33, lowStockThreshold: 5, tags: ["Brightening", "Routine Starter"], size: "100 g", origin: "India", madeInNepal: false, skinTypes: ["All Skin Types", "Combination"], concernTags: ["Brightening", "Routine Starter"], benefits: ["Weekly polish step", "Smooths rough-feeling areas", "Pairs with hydrating mask"], howToUse: ["Use once weekly on damp skin", "Massage gently for under a minute", "Avoid active breakouts"], ingredients: ["Mineral exfoliant", "Aloe extract", "Plant oils"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p038", name: "Fresh & More Himalayan Clay Face Mask", slug: "fresh-and-more-himalayan-clay-face-mask", description: "A Nepal-made clay mask for customers seeking natural weekly skincare rituals.", shortDescription: "Himalayan clay mask for oil control", sku: "GLM-SKN-FRM-CLAY-80", categorySlug: "skincare", brandName: "Fresh & More", basePrice: 115000, salePrice: 98000, costPrice: 48000, isFeatured: true, isBestSeller: false, isNewArrival: true, stockQuantity: 27, lowStockThreshold: 5, tags: ["Oil Control", "Natural", "Vegan", "new-arrival"], size: "80 g", origin: "Nepal", madeInNepal: true, skinTypes: ["Oily", "Combination"], concernTags: ["Oil Control", "Natural", "Vegan"], benefits: ["Clay-mask ritual", "Helps skin feel fresh", "Nepal-made story angle"], howToUse: ["Apply a thin layer after cleansing", "Leave for 8-10 minutes", "Rinse before fully dry"], ingredients: ["Himalayan clay", "Aloe extract", "Botanical blend"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p039", name: "Wild Earth Nepal Lavender Body Butter", slug: "wild-earth-nepal-lavender-body-butter", description: "A rich body-butter for local beauty and gifting collections.", shortDescription: "Lavender body butter from Nepal", sku: "GLM-BDY-WEN-LAV-120", categorySlug: "bodycare", brandName: "Wild Earth Nepal", basePrice: 145000, salePrice: 125000, costPrice: 65000, isFeatured: true, isBestSeller: false, isNewArrival: false, stockQuantity: 22, lowStockThreshold: 5, tags: ["Body Moisture", "Natural"], size: "120 g", origin: "Nepal", madeInNepal: true, skinTypes: ["Dry", "All Skin Types"], concernTags: ["Body Moisture", "Natural"], benefits: ["Richer body moisture", "Giftable local beauty angle", "Comforts dry elbows and knees"], howToUse: ["Massage onto clean dry skin", "Use extra on rough areas", "Best after shower"], ingredients: ["Shea butter", "Lavender oil", "Plant oils"], imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=900&q=86&fit=crop&auto=format" },
  { id: "p040", name: "Kathmandu Glow Bridal Lip & Cheek Tint", slug: "kathmandu-glow-bridal-lip-cheek-tint", description: "A Nepal-made tint for bridal, festival and everyday two-in-one color stories.", shortDescription: "Nepal-made 2-in-1 lip & cheek tint", sku: "GLM-MKP-KTG-TINT-10", categorySlug: "makeup", brandName: "Kathmandu Glow", basePrice: 99000, salePrice: 88000, costPrice: 35000, isFeatured: true, isBestSeller: false, isNewArrival: true, stockQuantity: 40, lowStockThreshold: 5, tags: ["Long Wear", "Festival", "Seamless Base", "new-arrival"], size: "10 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Long Wear", "Festival", "Seamless Base"], benefits: ["Two-in-one color", "Festival and wedding pouch ready", "Soft flushed finish"], howToUse: ["Tap a small amount on lips or cheeks", "Blend quickly", "Layer to build color"], ingredients: ["Color pigments", "Glycerin", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=900&q=86&fit=crop&auto=format" },
  { id: "p041", name: "Derma Lab 2% Salicylic Clarifying Toner", slug: "derma-lab-salicylic-clarifying-toner", description: "A BHA toner for oily-skin customers who want a clearer-looking routine.", shortDescription: "Salicylic acid toner for oily skin", sku: "GLM-SKN-DER-BHA-120", categorySlug: "skincare", brandName: "Derma Lab", basePrice: 175000, salePrice: 155000, costPrice: 95000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 26, lowStockThreshold: 5, tags: ["Pore Care", "Oil Control", "Acne Care"], size: "120 ml", origin: "Korea", madeInNepal: false, skinTypes: ["Oily", "Acne-Prone", "Combination"], concernTags: ["Pore Care", "Oil Control", "Acne Care"], benefits: ["Exfoliating-toner routine step", "Helps reduce congested look", "Use gradually"], howToUse: ["Use at night 2-3 times weekly", "Avoid eye and lip area", "Wear sunscreen next morning"], ingredients: ["Salicylic acid", "Green tea", "Panthenol"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p042", name: "GLAMO Edit Beginner Skincare Set", slug: "glamo-edit-beginner-skincare-set", description: "A routine-builder bundle to test sets, gifts and free-delivery threshold behavior.", shortDescription: "3-piece beginner skincare set", sku: "GLM-SET-BEG-03", categorySlug: "skincare", brandName: "GLAMO Edit", basePrice: 348000, salePrice: 299000, costPrice: 185000, isFeatured: true, isBestSeller: true, isNewArrival: false, stockQuantity: 19, lowStockThreshold: 5, tags: ["Routine Starter", "Hydration", "Sun Protection"], size: "3-piece set", origin: "Nepal/Korea", madeInNepal: false, skinTypes: ["All Skin Types", "Combination"], concernTags: ["Routine Starter", "Hydration", "Sun Protection"], benefits: ["Cleanser + moisturizer + SPF format", "Good for gifting", "Simplifies first routine"], howToUse: ["Cleanse morning and night", "Moisturize after cleansing", "Use SPF every morning"], ingredients: ["Routine bundle", "Supplier-approved INCI pending"], imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=900&q=86&fit=crop&auto=format" },
  { id: "p043", name: "Natura Nepal Rosemary Scalp Oil", slug: "natura-nepal-rosemary-scalp-oil", description: "A rosemary scalp-oil for haircare filters and local-beauty storytelling.", shortDescription: "Rosemary scalp oil for healthy hair", sku: "GLM-HAR-NAT-ROS-50", categorySlug: "haircare", brandName: "Natura Nepal", basePrice: 115000, salePrice: 99000, costPrice: 48000, isFeatured: false, isBestSeller: false, isNewArrival: true, stockQuantity: 31, lowStockThreshold: 5, tags: ["Scalp Care", "Natural", "new-arrival"], size: "50 ml", origin: "Nepal", madeInNepal: true, skinTypes: ["All Skin Types"], concernTags: ["Scalp Care", "Natural"], benefits: ["Pre-wash scalp massage", "Comforting herbal aroma", "Local wellness story"], howToUse: ["Massage into scalp before wash", "Leave for 30-60 minutes", "Shampoo thoroughly"], ingredients: ["Rosemary extract", "Coconut oil", "Jojoba oil"], imageUrl: "https://images.unsplash.com/photo-1526758097130-bab247274f58?w=900&q=86&fit=crop&auto=format" },
  { id: "p044", name: "Solar Care Waterlight SPF Body Lotion", slug: "solar-care-waterlight-spf-body-lotion", description: "A body sunscreen for shoppers needing SPF beyond the face.", shortDescription: "SPF body lotion for sun protection", sku: "GLM-BDY-SOL-SPF-150", categorySlug: "bodycare", brandName: "Solar Care", basePrice: 199000, salePrice: 175000, costPrice: 105000, isFeatured: false, isBestSeller: false, isNewArrival: false, stockQuantity: 28, lowStockThreshold: 5, tags: ["Sun Protection", "Body Moisture"], size: "150 ml", origin: "Thailand", madeInNepal: false, skinTypes: ["All Skin Types"], concernTags: ["Sun Protection", "Body Moisture"], benefits: ["Body SPF category coverage", "Light lotion feel", "Good for arms and neck"], howToUse: ["Apply before outdoor exposure", "Use generously on exposed areas", "Reapply after sweating"], ingredients: ["UV filters", "Aloe water", "Vitamin E"], imageUrl: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=900&q=86&fit=crop&auto=format" },
];

const CATEGORIES = [
  { id: "cat-skincare", name: "Skincare", slug: "skincare", description: "Cleansers, serums, moisturizers and SPF chosen for Nepal's climate." },
  { id: "cat-makeup", name: "Makeup", slug: "makeup", description: "Everyday base, lip, eye and cheek essentials." },
  { id: "cat-haircare", name: "Haircare", slug: "haircare", description: "Shampoo, oils and treatments for humidity and frizz." },
  { id: "cat-bodycare", name: "Bodycare", slug: "bodycare", description: "Creams, lotions and body rituals." },
  { id: "cat-fragrance", name: "Fragrance", slug: "fragrance", description: "Soft perfumes, mists and roll-ons." },
  { id: "cat-tools", name: "Tools", slug: "tools", description: "Brushes, sponges and beauty tools." },
];

const BRANDS_NAMES = [
  "Cetaphil", "COSRX", "Beauty of Joseon", "Innisfree", "The Ordinary", "CeraVe",
  "Bioderma", "La Roche-Posay", "Maybelline", "Lakme", "SUGAR Cosmetics", "Plum",
  "Minimalist", "Himalaya", "Mamaearth", "Aroma Magic", "Nivea", "Garnier",
  "L'Oreal Paris", "Swiss Beauty", "Kathmandu Glow", "Wild Earth Nepal",
  "GLAMO Edit", "Natura Nepal", "Luxe Aura", "Beauty Tools", "Derma Lab",
  "Fresh & More", "Solar Care", "Anua", "Himalayan Botanics",
];

async function main() {
  const dbUrl = process.env.TURSO_DB_URL;
  const authToken = process.env.TURSO_AUTH_TOKEN;
  const isLocalFile = dbUrl?.startsWith("file:");
  if (!dbUrl || (!authToken && !isLocalFile)) {
    console.error("TURSO_DB_URL (and TURSO_AUTH_TOKEN unless file: URL) must be set in backend/.env");
    process.exit(1);
  }

  const db = isLocalFile ? createClient({ url: dbUrl }) : createClient({ url: dbUrl, authToken });
  const now = new Date().toISOString();

  try {
    console.log("Seeding all 44 products into Turso DB (idempotent)...\n");

    // 1. Seed categories
    for (const cat of CATEGORIES) {
      await db.execute({
        sql: `INSERT INTO categories (id, name, slug, description, is_active, sort_order, created_at, updated_at)
              VALUES (?, ?, ?, ?, 1, ?, ?, ?)
              ON CONFLICT(id) DO NOTHING`,
        args: [cat.id, cat.name, cat.slug, cat.description, CATEGORIES.indexOf(cat) + 1, now, now],
      });
    }
    console.log(`\u2713 ${CATEGORIES.length} categories (skip if present)`);

    // 2. Seed brands
    const brandSlugify = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    for (const name of BRANDS_NAMES) {
      const id = `brand-${brandSlugify(name)}`;
      await db.execute({
        sql: `INSERT INTO brands (id, name, slug, description, is_active, created_at, updated_at)
              VALUES (?, ?, ?, ?, 1, ?, ?)
              ON CONFLICT(id) DO NOTHING`,
        args: [id, name, brandSlugify(name), `${name} beauty and personal care brand.`, now, now],
      });
    }
    console.log(`\u2713 ${BRANDS_NAMES.length} brands (skip if present)`);

    // 3. Seed all 44 products
    for (const p of ALL_PRODUCTS) {
      const brandSlug = p.brandName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
      const categoryId = CATEGORY_MAP[p.categorySlug] || "cat-skincare";

      const attributes: Record<string, unknown> = {
        size: p.size,
        origin: p.origin,
        subCategory: p.concernTags[0] || "General",
        skinType: p.skinTypes,
        benefits: p.benefits,
        ingredients: p.ingredients,
        howToUse: p.howToUse,
        madeInNepal: p.madeInNepal,
      };
      if (p.isBestSeller) attributes.isBestSeller = true;
      if (p.isNewArrival) attributes.isNewArrival = true;

      await db.execute({
        sql: `INSERT OR REPLACE INTO products
              (id, name, slug, description, short_description, sku, category_id, brand_id,
               base_price, sale_price, cost_price, currency, is_active, is_featured, is_digital,
               track_inventory, stock_quantity, low_stock_threshold, tags, attributes, created_at, updated_at)
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'NPR', 1, ?, 0, 1, ?, ?, ?, ?, ?, ?)`,
        args: [
          p.id, p.name, p.slug, p.description, p.shortDescription, p.sku,
          categoryId, `brand-${brandSlug}`,
          p.basePrice, p.salePrice, p.costPrice,
          p.isFeatured ? 1 : 0,
          p.stockQuantity, p.lowStockThreshold,
          JSON.stringify(p.tags), JSON.stringify(attributes),
          now, now,
        ],
      });

      // Primary image
      await db.execute({
        sql: `INSERT OR REPLACE INTO product_images
              (id, product_id, url, alt_text, sort_order, is_primary, created_at)
              VALUES (?, ?, ?, ?, 0, 1, ?)`,
        args: [`img-${p.id}`, p.id, p.imageUrl, p.name, now],
      });
    }
    console.log(`\u2713 ${ALL_PRODUCTS.length} products seeded with images`);

    // 4. Verify
    const verify = await db.execute({
      sql: `SELECT id, slug, stock_quantity FROM products WHERE id IN (${ALL_PRODUCTS.map(() => "?").join(",")}) ORDER BY id`,
      args: ALL_PRODUCTS.map((p) => p.id),
    });
    console.log(`\nVerification \u2014 ${verify.rows.length}/${ALL_PRODUCTS.length} products present in DB:`);
    for (const row of verify.rows) {
      const r = row as Record<string, unknown>;
      console.log(`   ${r.id}  ${r.slug}  stock=${r.stock_quantity}`);
    }

    if (verify.rows.length !== ALL_PRODUCTS.length) {
      const seeded = new Set(verify.rows.map((r: any) => r.id));
      const missing = ALL_PRODUCTS.filter((p) => !seeded.has(p.id)).map((p) => p.id);
      console.error(`\n\u26A0\uFE0F  ${missing.length} products did not persist: ${missing.join(", ")}`);
      process.exit(1);
    }

    console.log(`\n\u2705 All ${ALL_PRODUCTS.length} products seeded successfully.`);
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  } finally {
    try {
      const maybe = db.close() as unknown as Promise<void> | void;
      if (maybe && typeof (maybe as Promise<void>).then === "function") await maybe;
    } catch { /* best-effort cleanup */ }
  }
}

main();
