import type { LegalSection } from "@/components/legal/LegalLayout";
import { SITE_CONFIG } from "@/lib/config";

export const privacySections: LegalSection[] = [
  { id: "collection", title: "Information we collect", body: ["GLAMO NEPAL may collect customer details such as name, phone number, email address, delivery address, order preferences and support messages when customers shop, create an account or contact the store.", "Basic device and shopping activity information may be used to improve site performance, product discovery and customer support.", "In accordance with the Electronic Transactions Act 2065 (2008) of Nepal, we maintain records of electronic transactions and communications for the periods required by law."] },
  { id: "use", title: "How information is used", body: ["Customer data is used to process orders, coordinate delivery, verify payments, manage returns, answer support requests and improve the shopping experience.", "Marketing messages should only be sent with appropriate consent and a clear way to opt out, consistent with the Nepal Consumer Protection Act 2075 (2018)."] },
  { id: "sharing", title: "Service providers", body: ["Necessary order details may be shared with payment providers (Khalti, eSewa), delivery partners and support tools so GLAMO NEPAL can complete purchases and provide customer care.", "GLAMO NEPAL should not sell customer data.", "Data sharing with third parties complies with Nepalese law and is limited to what is necessary for order fulfilment, payment processing and legal compliance."] },
  { id: "security", title: "Security", body: ["Customer information is handled through secure connections (SSL/TLS), restricted staff access and careful operational procedures.", "Payment confirmations are verified with the selected payment provider before an order is fulfilled.", "We comply with the data protection provisions of the Electronic Transactions Act 2065 and take reasonable steps to protect personal information from unauthorised access, disclosure or loss."] },
  { id: "cookies", title: "Cookies and tracking", body: ["We use essential cookies to maintain your session, shopping cart and preferences.", "Analytics cookies help us understand how customers use our site so we can improve the experience.", "You may disable non-essential cookies through your browser settings."] },
  { id: "rights", title: "Your rights", body: ["You may request access to, correction of, or deletion of your personal data by contacting us.", "Under Nepalese law, consumers have the right to transparent information about how their data is handled.", "We will respond to data access requests within 30 days."] },
  { id: "contact", title: "Contact", body: [`For privacy questions, contact ${SITE_CONFIG.phone} or visit ${SITE_CONFIG.address}.`] },
];

export const termsSections: LegalSection[] = [
  { id: "scope", title: "Scope of service", body: ["These terms describe the GLAMO NEPAL ecommerce shopping experience for beauty, cosmetics and personal care products in Nepal.", "By placing an order, customers agree to provide accurate contact, delivery and payment information.", "These terms are governed by the laws of Nepal, including the Electronic Transactions Act 2065 (2008) and the Consumer Protection Act 2075 (2018)."] },
  { id: "orders", title: "Orders and pricing", body: ["Prices are shown in NPR (Nepalese Rupees) and include applicable taxes unless stated otherwise.", "GLAMO NEPAL may confirm, cancel or adjust orders according to stock availability, payment verification, courier coverage and any clear pricing error.", "Product availability and offers may change without prior notice.", "In the event of a pricing error, we reserve the right to cancel the order and notify the customer, as provided under the Consumer Protection Act 2075."] },
  { id: "payments", title: "Payments", body: ["Payment methods include Khalti, eSewa, Cash on Delivery (COD) and Cards where available.", "Orders paid online are processed after payment confirmation. COD orders may be confirmed by phone or message before dispatch.", "All digital payment transactions are subject to the Electronic Transactions Act 2065 and the regulations of Nepal Rastra Bank.", "GLAMO NEPAL does not store card details. Payments are processed through certified payment gateways."] },
  { id: "product-info", title: "Product information", body: ["GLAMO NEPAL aims to present product names, prices, descriptions, ingredients and usage guidance accurately.", "Customers should read labels and patch test new beauty products, especially if they have allergies or sensitive skin.", "Product images are for reference and may vary slightly from the actual item due to lighting, batch variation or packaging updates."] },
  { id: "disputes", title: "Dispute resolution", body: ["Any disputes arising from these terms shall be subject to the jurisdiction of the courts of Nepal.", "We encourage customers to contact us first to resolve any issues before seeking legal remedies.", "Consumer complaints may also be filed with the Department of Commerce, Supplies and Consumer Protection as provided under the Consumer Protection Act 2075."] },
  { id: "contact", title: "Contact", body: [`Questions can be sent to ${SITE_CONFIG.phone} or handled at ${SITE_CONFIG.address}.`] },
];

export const shippingSections: LegalSection[] = [
  { id: "coverage", title: "Delivery coverage", body: ["GLAMO NEPAL currently delivers within Kathmandu Valley.", "Some addresses may require phone confirmation before dispatch."] },
  { id: "timelines", title: "Estimated timelines", body: ["Kathmandu Valley orders are usually delivered within 1 to 2 business days after confirmation."] },
  { id: "fees", title: "Delivery fees", body: ["Delivery within Kathmandu Valley is available on all orders. Delivery fees depend on order size and payment method."] },
  { id: "pickup", title: "Store pickup", body: [`Store pickup may be arranged from ${SITE_CONFIG.address} after order confirmation.`] },
];

export const returnsSections: LegalSection[] = [
  { id: "eligibility", title: "Eligibility", body: ["Eligible products may be returned within 7 days if they are unused, unopened, sealed and in their original condition.", "Opened beauty, skincare, fragrance and hygiene-sensitive items may not be returnable unless they arrive damaged or incorrect.", "Under the Consumer Protection Act 2075 (2018) of Nepal, consumers have the right to return products that are defective, not as described, or delivered in a damaged condition."] },
  { id: "damaged", title: "Damaged or incorrect items", body: ["Customers should report damaged, missing or incorrect items within 48 hours of delivery with the order number, photos and delivery details.", "GLAMO NEPAL will review the issue and guide the customer on replacement, exchange or refund options.", "We will arrange return pickup for damaged items at no additional cost to the customer."] },
  { id: "refunds", title: "Refunds and exchanges", body: ["Refunds for Khalti, eSewa and card payments follow the payment provider's processing timeline, typically within 5–10 business days.", "COD returns may require manual verification before a refund or exchange is completed.", "Refunds are processed to the original payment method only, in compliance with Nepal Rastra Bank regulations.", "Exchange requests are subject to product availability."] },
  { id: "non-returnable", title: "Non-returnable items", body: ["Products marked as non-returnable on the product page cannot be returned unless they arrive damaged.", "Items returned without original packaging, tags or hygiene seals may not be accepted.", "Gift cards and digital products are non-refundable."] },
  { id: "process", title: "Return process", body: ["To initiate a return, contact our support team with your order number and reason for return.", "Once approved, we will provide return instructions and a return shipping label if applicable.", "Refunds are processed within 5 business days of receiving and inspecting the returned item."] },
  { id: "support", title: "Support", body: [`For support, contact ${SITE_CONFIG.phone} or ${SITE_CONFIG.instagramHandle} at ${SITE_CONFIG.social.instagram}.`] },
];
