import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '1.5rem',
        lg: '2rem',
      },
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'Cormorant Garamond', 'Georgia', 'serif'],
        body: ['var(--font-body)', 'Manrope', 'Inter', 'system-ui', 'sans-serif'],
        label: ['var(--font-body)', 'Manrope', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['var(--font-display)', 'Cormorant Garamond', 'Georgia', 'serif'],
        sans: ['var(--font-body)', 'Manrope', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        rose: {
          50: '#FFF1F3',
          100: '#FFE4E9',
          200: '#FECDD6',
          300: '#FDA4B4',
          400: '#FB7090',
          500: '#F43F64',
          600: '#D4798A',
          700: '#A84D5E',
          800: '#6B2535',
          900: '#421522',
          950: '#251016',
        },
        brand: {
          blush: '#F2D4DA',
          rose: '#D4798A',
          deep: '#A84D5E',
          dark: '#6B2535',
          gold: '#B8860B',
          'gold-light': '#D4A843',
          // Legacy aliases kept intentionally so older pages render instead of silently dropping classes.
          primary: '#D4798A',
          'primary-hover': '#A84D5E',
          'primary-light': '#F2D4DA',
          secondary: '#B8860B',
          border: '#F0E8E3',
          bgLight: '#FEFCFB',
          bgDark: '#1A0F0B',
          surfacePink: '#FFF1F3',
          surfaceWarm: '#FAF6F3',
          textPrimary: '#1A0F0B',
          textMuted: '#7B6259',
          'rose-dark': '#A84D5E',
          'rose-foreground': '#FEFCFB',
        },
        cream: {
          50: '#FEFCFB',
          100: '#FAF6F3',
          200: '#F0E8E3',
          300: '#E5D7D0',
          400: '#C4AFA7',
          500: '#9E857B',
          600: '#7B6259',
          700: '#5C4A44',
          800: '#3E2C26',
          900: '#2C1810',
        },
        ink: '#1A0F0B',
        gold: {
          DEFAULT: '#B8860B',
          light: '#D4A843',
        },
        primary: {
          DEFAULT: '#D4798A',
          light: '#F2D4DA',
          dark: '#A84D5E',
        },
        secondary: {
          DEFAULT: '#B8860B',
          light: '#D4A843',
        },
        neutral: {
          50: '#FEFCFB',
          100: '#FAF6F3',
          200: '#F0E8E3',
          300: '#E5D7D0',
          400: '#C4AFA7',
          500: '#9E857B',
          600: '#7B6259',
          700: '#5C4A44',
          800: '#3E2C26',
          900: '#2C1810',
          950: '#1A0F0B',
        },
        surface: '#FEFCFB',
        error: '#B4233A',
        success: '#58745A',
        admin: {
          success: '#4CAF82',
          'success-light': '#E8F5E9',
          warning: '#B8860B',
          'warning-light': '#FFF8E1',
          error: '#B4233A',
          'error-light': '#FFE4E9',
          info: '#5A6F88',
          'info-light': '#EAF0F5',
          neutral: '#7B6259',
          'neutral-light': '#FAF6F3',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        destructive: {
          DEFAULT: '#B4233A',
          foreground: '#FEFCFB',
        },
        muted: {
          DEFAULT: '#FAF6F3',
          foreground: '#9E857B',
        },
        accent: {
          DEFAULT: '#B8860B',
          foreground: '#1A0F0B',
        },
        popover: {
          DEFAULT: '#FEFCFB',
          foreground: '#1A0F0B',
        },
        card: {
          DEFAULT: '#FEFCFB',
          foreground: '#1A0F0B',
        },
      },
      spacing: {
        '4.5': '18px',
        '18': '72px',
        '22': '88px',
        '30': '120px',
      },
      fontSize: {
        'display-2xl': ['clamp(4rem, 10vw, 8rem)', { lineHeight: '0.95', letterSpacing: '-0.04em' }],
        'display-xl': ['clamp(3rem, 7vw, 5.5rem)', { lineHeight: '1', letterSpacing: '-0.03em' }],
        'display-lg': ['clamp(2.25rem, 5vw, 4rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-md': ['clamp(1.75rem, 3.5vw, 2.75rem)', { lineHeight: '1.1', letterSpacing: '-0.015em' }],
        'heading-xl': ['clamp(1.5rem, 2.5vw, 2.25rem)', { lineHeight: '1.15' }],
        'heading-lg': ['clamp(1.25rem, 2vw, 1.75rem)', { lineHeight: '1.2' }],
        'heading-md': ['clamp(1.125rem, 1.5vw, 1.375rem)', { lineHeight: '1.25' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.25' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75' }],
        'body-md': ['1rem', { lineHeight: '1.7' }],
        'body-sm': ['0.875rem', { lineHeight: '1.65' }],
        'label-lg': ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.1em' }],
        'label-md': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.12em' }],
        'label-sm': ['0.6875rem', { lineHeight: '1.4', letterSpacing: '0.15em' }],
        'price-xl': ['clamp(1.5rem, 2vw, 2rem)', { lineHeight: '1' }],
        'price-lg': ['clamp(1.25rem, 1.5vw, 1.5rem)', { lineHeight: '1' }],
        'price-md': ['1.125rem', { lineHeight: '1' }],
        'price': ['1.125rem', { lineHeight: '1' }],
        'nav': ['0.8125rem', { lineHeight: '1.4', letterSpacing: '0.12em' }],
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.04)',
        'card-hover': '0 8px 30px rgba(0,0,0,0.06)',
        'editorial': '0 30px 90px -65px rgba(91,36,51,0.38)',
        'soft': '0 2px 12px rgba(201,96,122,0.08)',
        'nav': '0 1px 0 rgba(0,0,0,0.06)',
      },
      zIndex: {
        'admin-overlay': '45',
        'admin-header': '30',
        'base': '0',
        'card': '10',
        'section-header': '20',
        'announcement': '40',
        'navbar': '50',
        'cart-backdrop': '55',
        'cart': '60',
        'menu-backdrop': '65',
        'menu': '70',
        'modal-backdrop': '75',
        'modal': '80',
        'toast': '90',
        'tooltip': '95',
        'whatsapp': '56',
        'back-to-top': '55',
        'skip-link': '100',
      },
      borderRadius: {
        'lg': '1.5rem',
        'md': '1rem',
        'sm': '0.75rem',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-in-left': 'slide-in-left 0.3s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'fade-in-up': 'fade-in-up 0.4s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
      },
      transitionTimingFunction: {
        'out': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [animate],
} satisfies Config;

export default config;